"""Generate sanguine/content/upgrades.toml (python tools/gen_upgrades.py > ...)."""
import sys
sys.path.insert(0, ".")
from tools.gen_ventures import V, sig

NAMES = [
 ("Darker Corner", "Whispered Invitation", "Ecstatic Silence"),
 ("Bass Tuned to a Pulse", "Velvet Private Room", "Guest List of the Damned"),
 ("Deeper Lattice", "Penance in Kind", "Absolution Futures"),
 ("Hotter Water", "Rose-Oil Monopoly", "Sighing Steam"),
 ("Cold-Chain Hex", "Donor Guilt Drive", "The Fridges Sing"),
 ("Better Wine", "Incense of Consent", "Ecstatic Liturgy"),
 ("Cooler Vault", "Vintage Scandal", "Grand Cru of Regret"),
 ("Compounding Kisses", "Interest in Kind", "Debts Collect Debts"),
 ("Tithe by Wrist", "Collar Ceremony", "Martyr Rota"),
 ("Black Lace Veils", "Weeping Rota", "Wake Without End"),
 ("Fever Dreams", "Delirium Discount", "Contagion of Desire"),
 ("Blood-Ink Refills", "Hidden Indenture", "Perpetual Clause"),
 ("Gilded Masks", "Anonymous Invitations", "The Unmasking Hour"),
 ("Sentence Commuted to Service", "Hung Jury (Willingly)", "Verdict in Advance"),
 ("Bone-Dust Interest", "Dynastic Mortgage", "Compound Ancestry"),
 ("Silk Rivalry", "Shared Bed, Shared Blood", "Jealousy Engine"),
 ("Sulphur Visas", "Tribute in Kind", "Demon at Dinner"),
 ("Tidal Gearing", "Eclipse Season", "The Kneeling Moon"),
 ("A Higher Dais", "Litany of Sighs", "Throne Warm From Below"),
 ("Hinges Oiled With Prayer", "Threshold Toll", "The Gate Reciprocates"),
]
TIERS = [(1e3, 3), (1e5, 3), (1e7, 5)]
GLOBAL = [
 ("Dominion of Velvet", 1e6, 2, "Everything is softer now, and closer to your teeth."),
 ("Rumour of Rapture", 1e9, 2, "Every rumour about you is true, and they all want it."),
 ("Court by Attrition", 1e12, 3, "Rivals have been quietly retired from the calendar."),
 ("Ritual Efficiency", 1e15, 3, "The liturgy is faster now. The moaning is the same."),
 ("Frictionless Surrender", 1e18, 3, "Resistance was a habit. The habit has been broken, gently."),
 ("Sovereign Appetite", 1e21, 3, "You feed at a rate you set."),
 ("Crimson Line Item", 1e24, 5, "A budget that writes its own devotion."),
 ("Hell Recognises Its Own", 1e27, 5, "It has read the ledger. It approves. It purrs."),
]

LAUNDER = [
 ("Glamour of Ordinary Things", 1e8, "You are the quiet neighbour. Everyone says so."),
 ("Forgotten Faces", 1e12, "Witnesses recall a pleasant dream, and nothing more."),
 ("Diffuse Guilt", 1e16, "Blame has been spread thin enough to see through."),
 ("Plausible Innocence Layer", 1e20, "A layer of the household whose only job is not to have seen."),
 ("Innocence of Innocence", 1e24, "Even the alibi has an alibi, in writing."),
]
HYPER = [
 ("The First Pact", 5, 1.25, "Signed young, and with enthusiasm."),
 ("Clause of Appetite", 15, 1.25, "Hunger is now a legal entitlement."),
 ("Devil's Advocate Retainer", 40, 1.5, "Your case has never been stronger. Your soul, anyone's guess."),
 ("Rights of the Damned", 100, 1.5, "It turns out they had rights. You now own them."),
 ("Hellfire, Amortised", 250, 2, "The flames are a line item, and a warm one."),
 ("Seal of the Archdevil", 600, 2, "Signed, sealed, delivered, and faintly moaning."),
 ("Eternal Indenture", 1500, 3, "Time was a term of the contract. It has been struck."),
 ("The Pit Was Always Here", 4000, 3, "It was beneath you before you were anyone. It was waiting to be climbed."),
]

FLAV = ["Marginal gains, but they linger.", "The numbers went up. So did the temperature.",
        "Approved unanimously by everyone present, and some who were not."]


def main():
    ups = []
    for i, (v, names) in enumerate(zip(V, NAMES)):
        base = sig(4 * 12.5 ** i)
        for k, (name, (f, m)) in enumerate(zip(names, TIERS)):
            ups.append((sig(base * f), dict(id=f"u{i+1:02d}_{k+1}", name=name, kind="venture", target=i, mult=m,
                        desc=f"{v[0]} output x{m}.", flavour=FLAV[k])))
    for k, (name, cost, m, fl) in enumerate(GLOBAL):
        ups.append((cost, dict(id=f"ug_{k+1}", name=name, kind="global", target=-1, mult=m,
                    desc=f"ALL output x{m}.", flavour=fl)))
    for k, (name, cost, fl) in enumerate(LAUNDER):
        ups.append((cost, dict(id=f"uh_{k+1}", name=name, kind="heat", target=-1, mult=0.8,
                    desc="Inquisition target x0.8 (less attention).", flavour=fl)))
    ups.sort(key=lambda t: t[0])
    hyper = [(cost, dict(id=f"uy_{k+1}", name=name, kind="hyper", target=-1, mult=m, currency="narrative",
             desc=f"ALL output x{m} (permanent, survives TORPOR).", flavour=fl))
             for k, (name, cost, m, fl) in enumerate(HYPER)]
    ups = hyper + ups
    out = ["# Generated by tools/gen_upgrades.py -- safe to hand-edit afterwards.", ""]
    for cost, u in ups:
        out += ["[[upgrade]]", f'id = "{u["id"]}"', f'name = "{u["name"]}"', f'kind = "{u["kind"]}"',
                f'target = {u["target"]}', f'mult = {float(u["mult"])}', f"cost = {cost!r}",
                f'currency = "{u.get("currency", "capital")}"',
                f'desc = "{u["desc"]}"', f'flavour = "{u["flavour"]}"', ""]
    print("\n".join(out))


main()
