"""Generate sanguine/content/annals.toml (python tools/gen_annals.py > ...).

Each feat is (stat, threshold, name, description). Every feat earned adds +2% to all output.
"""
FEATS = [
 ("exits", 1, "First Sleep", "Enter Torpor for the first time."),
 ("exits", 3, "A Habit of Centuries", "Enter Torpor 3 times."),
 ("exits", 10, "The Long Sleeper", "Enter Torpor 10 times."),
 ("exits", 25, "Insomnia, Reversed", "Enter Torpor 25 times."),
 ("exits", 60, "Sleep Is Practice", "Enter Torpor 60 times."),
 ("play_hours", 1, "An Hour of Dusk", "Play for 1 hour."),
 ("play_hours", 10, "A Night's Work", "Play for 10 hours."),
 ("play_hours", 40, "The Long Night", "Play for 40 hours."),
 ("play_hours", 100, "Resident", "Play for 100 hours."),
 ("play_hours", 250, "Furniture", "Play for 250 hours."),
 ("clicks", 100, "Hands-On", "Feed by hand 100 times."),
 ("clicks", 2000, "Calloused Fangs", "Feed by hand 2,000 times."),
 ("clicks", 25000, "Repetitive Strain, Eternal", "Feed by hand 25,000 times."),
 ("maxlog", 15, "Quadrillionaire", "Drink 1e15 Blood in total."),
 ("maxlog", 30, "Beyond the Decillion", "Drink 1e30 Blood in total."),
 ("maxlog", 50, "Larger Than Numbers", "Drink 1e50 Blood in total."),
 ("maxlog", 75, "Past the Edge of the Ledger", "Drink 1e75 Blood in total."),
 ("maxlog", 100, "A Googol of Appetite", "Drink 1e100 Blood in total."),
 ("tier", 5, "Reach Exceeds Grasp", "Hold a domain of tier 5."),
 ("tier", 10, "Ten Doors", "Hold a domain of tier 10."),
 ("tier", 20, "At the Gate", "Hold a domain of tier 20."),
 ("tier", 25, "Into the Below", "Hold a domain of tier 25."),
 ("tier", 30, "The Consummation", "Hold a domain of tier 30."),
 ("units_total", 500, "Population Control", "Hold 500 domain units at once."),
 ("units_total", 5000, "A Small Country", "Hold 5,000 domain units at once."),
 ("units_total", 20000, "Overpopulation", "Hold 20,000 domain units at once."),
 ("dossiers", 5, "Collector", "Unlock 5 Court files."),
 ("dossiers", 10, "Archivist of Sins", "Unlock 10 Court files."),
 ("dossiers", 15, "Nothing Left in the Dark", "Unlock every Court file."),
 ("events_seen", 10, "Used to Interruptions", "Resolve 10 incidents."),
 ("events_seen", 50, "A Full Mailbox", "Resolve 50 incidents."),
 ("machine_level", 1, "The Compact", "Sign the Compact."),
 ("machine_level", 4, "The Voice Shifts", "Reach machine level 4."),
 ("machine_level", 6, "Fully Possessed", "Reach machine level 6."),
 ("endless_levels", 10, "Never Quite Done", "Own 10 levels of Endless Rites."),
 ("endless_levels", 50, "Tithe Without End", "Own 50 levels of Endless Rites."),
 ("dynasties", 1, "A Dynasty Begins", "Found a Dynasty."),
 ("dynasties", 5, "Five Houses", "Found 5 Dynasties."),
 ("lineage_earned", 10, "Of Good Family", "Earn 10 Lineage."),
 ("lineage_earned", 100, "Old Blood", "Earn 100 Lineage."),
 ("ages_done", 1, "Patience, Rewarded", "Complete an Age."),
 ("ages_done", 10, "Time Is a Servant", "Complete 10 Ages."),
 ("hunts_done", 1, "First Trial", "Complete a Hunt."),
 ("hunts_done", 10, "Seasoned Hunter", "Complete 10 Hunts."),
 ("hunts_done", 50, "The Hunt Knows Your Name", "Complete 50 Hunts."),
]
TITLES = [(0, "Fledgling"), (5, "Stalker"), (12, "Predator"), (20, "Elder"), (30, "Ancient"), (40, "Sovereign")]


def main():
    out = ["# Generated by tools/gen_annals.py -- safe to hand-edit afterwards.",
           "# Each feat earned: +2% to all output. Stats are computed in engine/annals.py.", ""]
    for i, (stat, at, name, desc) in enumerate(FEATS):
        out += ["[[feat]]", f'id = "f{i + 1:02d}"', f'name = "{name}"', f'stat = "{stat}"', f"at = {at}",
                f'desc = "{desc}"', ""]
    for at, name in TITLES:
        out += ["[[title]]", f"at = {at}", f'name = "{name}"', ""]
    print("\n".join(out))


if __name__ == "__main__":
    main()
